name: Web

on:
  push:
    branches:
      - pre-prod
  pull_request:
    branches:
      - pre-prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1

      - run: npm install
      - run: npm run-script build
      - uses: actions/upload-artifact@v2
        with:
          name: Webapp
          path: dist

  release:
    if: github.ref == 'refs/heads/pre-prod'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: .
      - run: ng deploy --base-href=/Les-gradins-web/
